Link loading components
clearfeld/control-ui pull request #23
Opened 2024-11-16 20:46 UTC by AaronPatterson1

2024-11-17 17:40 UTC, clearfeld requested changes

2024-11-17 17:40 UTC, clearfeld commented on packages/_site/src/pages/components/loading/index.tsx
> +                                title="Default"
If you're adding properties to the component than it isn't default, name it after the variant form.

2024-11-17 17:40 UTC, clearfeld commented on packages/_site/src/pages/components/loading/index.tsx
> +                                title="Default"
If you're adding properties to the component than it isn't default, name it after the variant form.

2024-11-17 17:40 UTC, clearfeld commented on packages/_site/src/pages/components/loading/index.tsx
> +                                description="The small version of the loading component."
If this one is default leave the default in the description.

2024-11-17 17:40 UTC, clearfeld commented on packages/_site/src/pages/components/link/index.tsx
> +`}
This won't show a visited Link by default. When a user views this a first time its going to look like a normal link until they actually visit it. This needs to have an explicit forced style and state to display correctly consistently.

2024-11-17 19:46 UTC, AaronPatterson1 commented
Made requested changes. please check again.

2024-11-18 06:31 UTC, clearfeld requested changes

2024-11-18 06:31 UTC, clearfeld commented on packages/_site/src/pages/components/link/index.tsx
> +                                    <Link href="https://github.com/clearfeld" style={{color: "#006699"}}>Default</Link>
Use the css variable colors.

2024-11-18 06:31 UTC, clearfeld commented on packages/_site/src/pages/components/link/index.tsx
> +                                    <Link href="/components/link/examples" style={{color: "#b6aef2"}}>Visited</Link>
Same as above

2024-11-19 00:01 UTC, AaronPatterson1 commented
Made changes, please check again.

2024-11-19 06:19 UTC, clearfeld approved these changes

2024-11-19 06:19 UTC, merged