Adding Lozenge element
clearfeld/control-ui pull request #24
Opened 2024-11-16 21:35 UTC by AaronPatterson1

2024-11-17 17:45 UTC, clearfeld requested changes

2024-11-17 17:45 UTC, clearfeld commented on packages/_site/src/pages/components/lozenge/index.tsx
> +                description="A colored, emphasized label encased in a rounded rectangle element."
Description that should be used:
"A lozenge is a visual indicator used to highlight an item's status for quick recognition."

2024-11-17 17:45 UTC, clearfeld commented on packages/_site/src/pages/components/routes_list_docs_components.ts
> +    description: "A colored, emphasized label encased in a rounded rectangle element.",
Same as above description.

2024-11-17 17:45 UTC, clearfeld commented on packages/_site/src/pages/components/lozenge/index.tsx
> +            isBold={true}
Don't use the isBold here.

2024-11-17 17:45 UTC, clearfeld commented on packages/_site/src/pages/components/lozenge/index.tsx
> +                                description="Blue Lozenged element, indicated removal or error, boldened."
A blue lozenge doesn't indicate removal or an error.

2024-11-17 17:45 UTC, clearfeld commented on packages/_site/src/pages/components/lozenge/index.tsx
> +                                description="Red Lozenged element, indicated removal or error, boldened."
Lozenges don't indicate errors.

2024-11-17 17:45 UTC, clearfeld commented on packages/_site/src/pages/components/lozenge/index.tsx
> +                                description="Red Lozenged element, indicated removal or error."
Lozenges don't indicate errors.

2024-11-17 19:57 UTC, AaronPatterson1 commented
Fixed, please check again.

2024-11-18 06:32 UTC, clearfeld approved these changes

2024-11-18 06:32 UTC, merged