Popover
clearfeld/control-ui pull request #25
Opened 2024-11-17 02:12 UTC by AaronPatterson1

2024-11-17 17:47 UTC, clearfeld requested changes

2024-11-17 17:47 UTC, clearfeld commented on packages/_site/src/pages/components/popover/index.tsx
> +                description="A button that can be used to display some content on top of another."
Use this description:
"Displays rich content in a portal, triggered by a button."

2024-11-17 17:47 UTC, clearfeld commented on packages/_site/src/pages/components/routes_list_docs_components.ts
> +    description: "A button that can be used to display some content on top of another.",
Same as above.

2024-11-17 20:12 UTC, AaronPatterson1 commented
Fixed, please check again.

2024-11-18 06:32 UTC, clearfeld approved these changes

2024-11-18 06:34 UTC, merged