Adding switch component
clearfeld/control-ui pull request #30
Opened 2024-11-17 22:25 UTC by AaronPatterson1

2024-11-18 06:43 UTC, clearfeld requested changes

2024-11-18 06:43 UTC, clearfeld commented on packages/_site/src/pages/components/routes_list_docs_components.ts
> +    description: "A switch is a control used to toggle between enabled or disabled states.",
Let's change this to true and false state, since we use a disabled prop to fully disabled interactive off the component, for better clarity.

2024-11-18 06:43 UTC, clearfeld commented on packages/_site/src/pages/components/switch/index.tsx
> +                                description="For more important actions, set size to medium."
The sizing isn't related to the importance of an action. That portion of the description can be removed same goes for the other descriptions.

2024-11-18 06:43 UTC, clearfeld commented on packages/_site/src/pages/components/switch/index.tsx
> +                                description="When the switch selection has no need to be changable, set the state to disabled."
Change state to prop.

2024-11-18 06:43 UTC, clearfeld commented on packages/_site/src/pages/components/switch/index.tsx
> +`}
Remove this, its redundant since we already have the disabled prop example just above it.

2024-11-19 01:04 UTC, AaronPatterson1 commented
Changes made, please check again.

2024-11-19 06:20 UTC, clearfeld approved these changes

2024-11-19 06:20 UTC, merged